name: html_to_text
description: Convert html to text.
version: 0.1.0
#homepage:

environment:
  sdk: ">=2.19.3 <3.0.0"
  flutter: ">=3.7.6"

dependencies:
  csslib: ^0.17.2
  flutter:
    sdk: flutter
  from_css_color: ^2.0.0
  html: ^0.15.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
