name: html_to_text
description: Convert html to text.
version: 0.1.0
#homepage:

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  csslib: ^1.0.0
  flutter:
    sdk: flutter
  from_css_color: ^2.0.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
